# Generated by Django 4.2.16 on 2024-11-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in preparazione', 'in preparazione'), ('pronto', 'pronto'), ('nel carrello', 'nel carrello')], default='nel carrello', max_length=20, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('antipasti', 'antipasti'), ('primi', 'primi'), ('secondi', 'secondi'), ('dolci', 'dolci'), ('bevande', 'bevande')], max_length=20, null=True)),
                ('descrizione', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ordineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordini.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordini.prodotto')),
            ],
        ),
    ]
