# Generated by Django 4.2.16 on 2024-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0004_alter_prodotto_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(choices=[('antipasti', 'antipasti'), ('primi', 'primi'), ('secondi', 'secondi'), ('dolci', 'dolci'), ('bevande', 'bevande')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
