# Generated by Django 4.2.16 on 2024-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0005_alter_prodotto_categoria_alter_prodotto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='tempo',
            field=models.IntegerField(null=True),
        ),
    ]
