# Generated by Django 4.2.16 on 2024-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_alter_cliente_cognome_alter_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='immagine',
            field=models.ImageField(blank=True, default='static/images/basic.png', null=True, upload_to=''),
        ),
    ]
