# Generated by Django 4.2.16 on 2024-12-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_alter_cliente_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='immagine',
            field=models.ImageField(blank=True, default='static/images/basic.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
