# Generated by Django 4.2.16 on 2024-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0008_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
