# Generated by Django 4.2.16 on 2024-11-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=50, null=True)),
                ('descrizione', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in attesa', 'in attesa'), ('approvata', 'approvata'), ('rifiutata', 'rifiutata')], default='in attesa', max_length=20, null=True)),
                ('descrizione', models.CharField(max_length=200, null=True)),
                ('motivazione', models.CharField(blank=True, max_length=200, null=True)),
                ('annuncio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ristoratore.annuncio')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.cliente')),
            ],
        ),
    ]
